### ISSUE TITLE
Compile failure with pre-AMP/FTP `base`

### ISSUE THREAD

**Issue by hvr** [javgh/watchdog#3]
See e.g.

```
Configuring component lib from watchdog-0.3...
Preprocessing library watchdog-0.3...
[1 of 1] Compiling Control.Watchdog ( Control/Watchdog.hs, /tmp/matrix-worker/1496735923/dist-newstyle/build/x86_64-linux/ghc-7.8.4/watchdog-0.3/build/Control/Watchdog.o )

Control/Watchdog.hs:265:39:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Control.Monad.State.Strict)
```

I've already revised the meta-data on Hackage (see https://hackage.haskell.org/package/watchdog-0.3/revisions/) so there's no immediate need to upload a new release (if it's just for the meta-data).

See also https://matrix.hackage.haskell.org/package/watchdog to get an overview

**Comment by javgh** [comment]
Thank you for the report and already fixing it on Hackage! I'll include the revised dependencies in future releases.
